//
//  WidgetTips+Hospitality.swift
//  DECAStudyWidget
//
//  Hospitality and Tourism cluster. Original study notes written for this app —
//  not official DECA Ontario or DECA Inc. material.
//

import Foundation

extension WidgetTips {
    static let hospitality: [String] = [
        "Hotel rooms are perishable inventory: an unsold room-night can never be sold again.",
        "Average daily rate is room revenue divided by rooms sold. Occupancy is rooms sold over rooms available.",
        "RevPAR multiplies occupancy by average daily rate, so it catches the trade-off between filling and pricing.",
        "Selling every room cheaply and selling few rooms dearly can produce the same RevPAR. Only one builds a brand.",
        "Overbooking deliberately accepts more reservations than there are rooms, to offset cancellations and no-shows.",
        "Walking a guest means paying for a comparable room at another property when yours has none left.",
        "The night audit balances the day's guest accounts and posts room charges.",
        "A guest folio is the running account of one guest's charges and payments.",
        "A property management system handles reservations, room assignment, guest accounts and reporting.",
        "A pre-authorisation hold confirms the card is valid and reserves funds for the stay and likely incidentals.",
        "Upselling at check-in offers a better room or an added amenity — it is not charging more for the same thing.",
        "A non-refundable advance rate captures price-sensitive demand early while protecting rooms for late bookers.",
        "A minimum-length-of-stay restriction stops one-night bookings blocking the highest-demand nights.",
        "Displacement analysis asks whether taking a group booking pushes out higher-rated transient business.",
        "A pace report compares bookings on the books against the same point last year, to guide pricing now.",
        "Business travel is less price-sensitive and books close in. Leisure travel is the opposite.",
        "Shoulder season is the period either side of peak. Marketing it fills the calendar without discounting peak.",
        "Ancillary revenue is everything besides the room: parking, spa, resort fees, in-room dining.",
        "Relying heavily on online travel agencies costs commission and loses the direct guest relationship.",
        "A tour operator assembles and packages the components of a trip. A travel agent sells them.",
        "Leakage is visitor spending that leaves the local economy, often to foreign-owned operators.",
        "The multiplier effect is visitor money circulating locally as businesses and staff spend it again.",
        "Carrying capacity is the visitation a destination can take without unacceptable damage.",
        "Overtourism is visitor volume exceeding what infrastructure and residents can comfortably absorb.",
        "Ecotourism focuses on natural areas while minimising impact and benefiting local communities.",
        "Tourism brings employment and tax revenue, and also pressure on housing costs and infrastructure.",
        "Seasonality is the industry's structural problem: fixed costs run all year, revenue does not.",
        "A destination marketing organisation's stakeholders include hotels, attractions, transport and residents.",
        "Destination positioning has to rest on attributes the place genuinely has and rivals cannot claim.",
        "Familiarisation trips let travel media and agents experience a destination so they can recommend it credibly.",
        "User-generated content carries the credibility of a real visitor, which an advertisement cannot buy.",
        "Experiential tourism sells the doing, not the seeing — a harvest day rather than a view of a farm.",
        "Indigenous cultural experiences must be Indigenous-led, with communities controlling how they are represented.",
        "Campaign success is measured in incremental visitor spending, not in impressions or press releases.",
        "The temperature danger zone runs from 4°C to 60°C. Food should spend as little time in it as possible.",
        "Hot holding is above 60°C. Cold holding is below 4°C. Anything between is the danger zone.",
        "Cooked food must be cooled quickly — shallow pans, not a deep covered container left on the counter.",
        "Cross-contamination is prevented with separate boards and utensils for raw proteins and ready-to-eat food.",
        "Changing gloves between raw chicken and salad is not optional; the pathogens travel on the gloves.",
        "HACCP identifies hazards and controls them at critical points in the process, not by inspecting the last dish.",
        "The seven HACCP principles start with hazard analysis and end with record keeping.",
        "Temperature logs for cooking, cooling and holding are the record that demonstrates due diligence.",
        "Labelling prepared items with a date is what makes the safe holding period enforceable.",
        "Undisclosed allergens can cause a severe or fatal reaction. Disclosure is a safety duty, not a courtesy.",
        "The correct dishwashing sequence is wash, rinse, sanitise, then air dry. Towel drying reintroduces bacteria.",
        "FIFO — first in, first out — rotates stock so the oldest is used before it expires.",
        "Personal hygiene, handwashing and staying home when ill prevent more outbreaks than any single procedure.",
        "A food handler certificate is a minimum, not a substitute for daily supervision.",
        "Standardised recipes hold quality, portion size and food cost steady every time a dish is made.",
        "Food cost percentage is food cost divided by food sales. Portion control is the fastest lever on it.",
        "Menu engineering sorts dishes by popularity and profitability into stars, plow horses, puzzles and dogs.",
        "A star is popular and profitable — feature it. A dog is neither — cut it.",
        "A plow horse sells well at low margin. Reprice or re-engineer it before removing it.",
        "A puzzle is profitable but unpopular. Move it on the menu or explain it better before dropping it.",
        "Waste, theft and over-portioning erode margin faster than the price of ingredients.",
        "A food waste audit finds where food is lost, so both cost and environmental impact fall.",
        "Yield percentage accounts for trim and waste, so the cost of a portion reflects what you actually serve.",
        "Front of house and back of house succeed or fail together. Neither can rescue the other alone.",
        "Table turnover matters in a restaurant the way occupancy matters in a hotel.",
        "A banquet event order specifies every operational detail of an event for the venue's departments.",
        "An attrition clause requires payment if a group fills fewer rooms than it contracted for.",
        "Force majeure covers extraordinary events beyond either party's control that prevent performance.",
        "A run of show sequences an event minute by minute so every party acts in the right order.",
        "A site inspection verifies that space, access, capacity and services genuinely match the requirements.",
        "Theatre style suits a keynote. Classroom style suits note-taking. U-shape suits discussion.",
        "A hybrid event combines in-person attendance with a live virtual audience, and needs both planned properly.",
        "Accessibility planning includes step-free access, captioning, quiet space and clear dietary accommodation.",
        "Accommodating an accessibility request is a legal and service obligation, not a favour.",
        "A contingency plan manages weather, vendor failure and power loss before they happen, not after.",
        "A post-event evaluation is most useful while the event is fresh and can still shape the next one.",
        "A meeting planner trading room rate against food and beverage commitment works because hotels value total spend.",
        "Guest complaints handled during the stay cost far less than a review written after it.",
        "The best first response to a complaint is to listen fully, acknowledge the problem and apologise.",
        "Answer a negative review publicly, address the specific issue, and invite the guest to contact you directly.",
        "When a third-party booking site causes the problem, fix it for the guest first and pursue the site after.",
        "Empowering staff to resolve issues up to a set limit solves problems while the guest is still on site.",
        "Personalising a returning guest's stay from stored preferences signals recognition, which builds loyalty.",
        "Recovering a loyalty member's complaint matters most: their defection costs far more than a single stay.",
        "A seamless stay means the handoffs between departments were invisible to the guest, not that nobody spoke.",
        "Net promoter score tracked over time reveals satisfaction trends before they show up in revenue.",
        "Greenwashing is claiming environmental credentials the business does not actually deliver.",
        "Heating, ventilation and air conditioning is the largest single energy draw in a typical full-service hotel.",
        "Linen reuse programmes cut both laundry cost and water use, which is why they are offered as a choice.",
        "Bulk amenity dispensers remove far more single-use plastic than any other change in a guest room.",
        "Local sourcing cuts transport emissions and keeps spending in the local economy.",
        "A sustainability certification is credible when awarded independently against published criteria and re-audited.",
        "Employing and training local residents keeps income and career progression within the host community.",
        "The business case for sustainability is strongest where an initiative cuts cost and improves perception at once.",
        "Timed entry to a fragile site protects its carrying capacity and its long-term viability as an attraction.",
        "Cross-training staff across departments lets a seasonal property deploy people as demand shifts.",
        "High turnover is the industry's chronic cost. Scheduling, training and respect move it more than pay alone.",
        "Tipping practice varies by country. Knowing local norms is part of serving international guests well.",
        "A concierge's value is local knowledge and connections, which no search engine fully replaces.",
        "Duty of care means a venue is responsible for the reasonable safety of guests on its premises.",
        "Serving alcohol carries legal liability. Refusing service to an intoxicated guest is part of the job.",
        "Guest data must be protected the same as any other personal information, including at the front desk.",
        "A no-show and a cancellation are different events with different revenue consequences. Track them separately.",
        "Group business smooths seasonality but at a lower rate. The mix, not either alone, is the strategy.",
        "The guest remembers how a problem was handled far longer than they remember the problem.",
    ]
}
