//
//  WidgetTips+Personal.swift
//  DECAStudyWidget
//
//  Personal Financial Literacy cluster. Original study notes written for this
//  app — not official DECA Ontario or DECA Inc. material, and not financial
//  advice.
//

import Foundation

extension WidgetTips {
    static let personalFinance: [String] = [
        "Gross pay is before deductions. Net pay is what actually lands in the account.",
        "CPP and EI on a Canadian pay stub are mandatory contributions to public pension and employment insurance.",
        "Income tax withheld at source is an estimate. Filing a return settles the difference either way.",
        "A student who earned income should file even when no tax is owed — refunds and RRSP room depend on it.",
        "Canada uses a progressive tax system: higher portions of income are taxed at higher rates, not the whole.",
        "Your marginal rate applies to the next dollar earned. Your average rate is what you actually paid overall.",
        "A tax deduction reduces taxable income. A tax credit reduces the tax owed directly.",
        "The 50/30/20 guideline splits income into 50% needs, 30% wants, 20% savings and debt repayment.",
        "A fixed expense stays roughly level each month. A variable expense moves with how much you use.",
        "Tracking spending for one month before budgeting reveals where money actually goes.",
        "Paying yourself first moves money to savings the moment income arrives, before discretionary spending.",
        "A sinking fund saves regularly for a known future expense, so it never becomes an emergency.",
        "An emergency fund is for the unknown. A sinking fund is for the known. Both are needed.",
        "Financial planners commonly suggest three to six months of essential expenses in an emergency fund.",
        "An emergency fund belongs in an accessible account whose value does not fluctuate.",
        "Lifestyle inflation is spending rising to match every raise, so saving never actually improves.",
        "Someone whose income varies should budget from a conservative month and save the surplus from strong ones.",
        "A financial goal is far more likely to be met when it is specific, measurable and has a deadline.",
        "Net worth is total assets minus total liabilities. It is the single clearest measure of financial progress.",
        "An appreciating asset tends to gain value. A car is the depreciating asset most people own first.",
        "A chequing account is built for frequent transactions. A savings account is built to earn interest.",
        "Overdraft protection covers transactions beyond the balance for a fee, preventing declined payments.",
        "Compare bank accounts on the fees you will actually trigger, not on the advertised headline.",
        "Simple interest only ever pays on what you put in. Compound interest pays on the interest as well.",
        "Compound interest works against a borrower when unpaid interest joins the balance and is charged again.",
        "The Rule of 72 estimates doubling time: divide 72 by the annual rate of return.",
        "Starting to invest at 20 rather than 30 matters because the extra decade of compounding does most of the work.",
        "An annual percentage rate expresses the yearly cost of borrowing, which makes different offers comparable.",
        "A credit score reflects payment history, amounts owed, length of history, new credit and credit mix.",
        "Payment history is the largest single factor in a credit score. One missed payment outweighs a lot of good ones.",
        "Credit utilization is the share of available credit currently being used. Below 30% is a common guideline.",
        "Closing an old credit card can lower a score by shortening average account age and cutting available credit.",
        "A hard inquiry happens when a lender checks your report for an application. Checking your own score does not.",
        "Dispute an error on a credit report with the bureau, and provide supporting documentation.",
        "A secured credit card requires a cash deposit that generally sets the limit. It is a way to build history.",
        "Paying a credit card in full each month means no interest at all. Paying the minimum means years of it.",
        "The minimum payment is designed to keep the balance alive, not to clear it.",
        "The avalanche method pays the highest interest rate first, which minimises total interest paid.",
        "The snowball method pays the smallest balance first, which minimises the time to a visible win.",
        "A payday loan's effective annual rate is extremely high, and rollovers can trap a borrower in a cycle.",
        "Buy-now-pay-later becomes dangerous when several small instalment plans overlap and hide the total owed.",
        "Consolidating debts helps when it lowers the overall rate and simplifies repayment, without new borrowing.",
        "A co-signer is equally responsible for repayment if the primary borrower defaults.",
        "Someone with expensive card debt and idle savings above their emergency reserve should usually clear the debt.",
        "A variable rate moves with a benchmark, so payments or interest costs can rise as well as fall.",
        "Diversification spreads investments so a single poor performer has limited effect.",
        "Diversification reduces risk specific to one company. It cannot remove market risk.",
        "Higher potential returns generally come with a higher risk of loss. Anything promising both is a warning sign.",
        "A young investor with a long horizon can tolerate more short-term volatility, because there is time to recover.",
        "Dollar-cost averaging invests a fixed amount at regular intervals regardless of price.",
        "Inflation risk means money in low-return accounts loses purchasing power even while the balance rises.",
        "A GIC pays a set rate over a fixed term. It is a deposit, not an ownership stake.",
        "A bondholder is a lender to the issuer. A shareholder is a part owner.",
        "A mutual fund pools money from many investors to buy a diversified portfolio managed on their behalf.",
        "An index fund tracks a market index, usually at a much lower fee than an actively managed fund.",
        "A management expense ratio is deducted every year, so its effect compounds over decades.",
        "A capital gain is realised only when you sell for more than you paid. Paper gains are not taxed.",
        "Asset allocation is how a portfolio is divided among stocks, bonds and cash. It drives most of the outcome.",
        "Rebalancing moves holdings back to the target allocation after market movements shift them.",
        "TFSA withdrawals are generally tax-free. RRSP contributions are generally tax-deductible.",
        "Withdrawing from a TFSA restores that contribution room on 1 January of the following year, not immediately.",
        "An RRSP defers tax to retirement. A TFSA pays tax now and shelters everything after.",
        "An RESP is attractive because government grants add to contributions and growth is sheltered until withdrawal.",
        "Old Age Security and the Canada Pension Plan are public programmes that supplement personal savings.",
        "An employer match on a retirement contribution is an immediate return on your own money.",
        "Behavioural bias most commonly leads people to sell during declines and buy after rises.",
        "Automatic transfers to savings work because they remove the monthly decision and make saving the default.",
        "The single habit with the greatest long-term effect is saving and investing consistently over many years.",
        "An insurance premium keeps coverage in force. A deductible is what you pay before coverage applies.",
        "Term life insurance covers a set period and costs less for the same death benefit than permanent cover.",
        "Permanent life insurance builds cash value, which is why it costs more.",
        "Disability insurance protects against losing income because illness or injury prevents working.",
        "A young driver's premium is higher because that group statistically has more and costlier claims.",
        "A landlord's policy covers the building, not the tenant's possessions or personal liability.",
        "Tenant insurance is usually inexpensive relative to the value of everything in the unit.",
        "Health and dental coverage from an employer is part of total compensation, not a perk.",
        "Comparing job offers on salary alone ignores benefits, pension matching, hours, commuting and growth.",
        "A warranty covers defects in materials or workmanship for a stated period. Insurance covers accidental loss.",
        "An extended warranty is worth its price only when the repair cost and failure rate justify it.",
        "Comparison shopping should weigh total cost: delivery, warranty, financing charges and running costs.",
        "The cheapest purchase price and the lowest total cost are frequently different products.",
        "Impulse purchases are what a waiting period of a day or two is designed to catch.",
        "Identity theft protection begins with strong unique passwords, guarded personal information and monitored accounts.",
        "A phishing message creates urgency so the recipient reveals credentials without thinking.",
        "No legitimate institution asks for a password or a full card number by email or text.",
        "The most reliable protection against fraud is slowing down, verifying independently and refusing to be rushed.",
        "If an offer requires acting immediately and paying by gift card or transfer, it is a scam.",
        "Read the terms before signing: fees, rate changes and penalties are disclosed there, not in the advertising.",
        "An adviser paid by commission on what they sell faces a conflict between your interest and their product.",
        "A fee-only adviser is paid by you, which removes that particular conflict.",
        "Renting can be the better choice when you may move within a few years or lack a down payment and reserve.",
        "A mortgage term is the length of the current rate agreement. Amortisation is the time to pay it off entirely.",
        "A longer amortisation lowers the monthly payment and increases the total interest paid.",
        "A down payment below 20% generally requires mortgage default insurance in Canada.",
        "Closing costs — land transfer tax, legal fees, inspection — are on top of the down payment.",
        "A scholarship is generally awarded on merit. A bursary is generally awarded on financial need.",
        "The complete cost of post-secondary study includes tuition, housing, materials, transport and forgone earnings.",
        "Exhaust grants, scholarships and bursaries before borrowing, then borrow only what is actually needed.",
        "Canadian student loan repayment typically begins after a grace period following full-time study.",
        "A co-op or apprenticeship offsets cost with paid work terms and builds experience at the same time.",
        "Judge a credential by what its graduates actually earn and how employable they are, not by prestige.",
        "A will directs how assets are distributed and can name guardians and an executor.",
        "Naming a beneficiary on a registered account lets the asset pass directly, outside the estate.",
    ]
}
