//
//  WidgetTips+Entrepreneurship.swift
//  DECAStudyWidget
//
//  Entrepreneurship cluster. Original study notes written for this app — not
//  official DECA Ontario or DECA Inc. material.
//

import Foundation

extension WidgetTips {
    static let entrepreneurship: [String] = [
        "An executive summary presents the concept, the market and the money needed — and is written last.",
        "A feasibility study asks whether the concept is workable and likely to be profitable, before the plan.",
        "If feasibility says no, revise or abandon before committing capital. Proceeding to justify the study is sunk cost.",
        "Technical feasibility asks whether you can actually build and deliver it with the technology and skills to hand.",
        "Market feasibility asks whether enough people will pay. They are separate questions with separate answers.",
        "A business model canvas fits on one page, which is what makes its assumptions quick to test and revise.",
        "The value proposition states the specific benefit the customer gets and why it beats the alternatives.",
        "Investors read the management section closely because team credentials predict execution.",
        "The operations section describes how the product is produced or delivered, and what that requires.",
        "Financial projections need the assumptions written beside them, or nobody can judge whether they are plausible.",
        "Total addressable market is the revenue available if you captured the entire market. You will not.",
        "Serviceable market is the slice you can actually reach. It is the number worth planning against.",
        "A minimum viable product tests the core assumption with the least time and money at risk.",
        "An MVP is not a cheap version of the finished product. It is an experiment with a specific question.",
        "Build, measure, learn: build the smallest thing that tests an assumption, measure it, then adjust.",
        "A concierge MVP delivers the service manually to early customers before automating anything.",
        "A pivot changes something fundamental in the model in response to what was learned, not to what was hoped.",
        "The strongest evidence of demand is somebody pre-ordering or paying a deposit. Compliments are not evidence.",
        "Friends saying an idea sounds good is the weakest signal in the whole process.",
        "A vanity metric looks impressive and informs no decision. Followers without conversion is the classic.",
        "Product-market fit shows as customers using the product repeatedly and being disappointed if it vanished.",
        "Scaling before product-market fit accelerates spending on something customers do not yet keep using.",
        "Early adopters tolerate rough edges and give detailed feedback in exchange for solving their problem sooner.",
        "Early adopters are not the mass market. What delights them may not persuade anyone else.",
        "Feature creep consumes limited resources and delays learning whether the core idea even works.",
        "A problem customers call annoying but tolerable is a hard sell. People pay to fix pain, not irritation.",
        "Bootstrapping funds growth from savings and reinvested revenue rather than outside investment.",
        "Bootstrapping keeps control and limits speed. Venture capital does the reverse.",
        "Venture capital seeks ventures that can scale fast to a large market and return a multiple on exit.",
        "Angel investors invest their own money earlier and smaller than a venture fund will.",
        "Crowdfunding backers may receive the product early, an ownership stake, or nothing but goodwill — check which.",
        "A term sheet is a mostly non-binding outline of proposed investment terms.",
        "Due diligence verifies the venture's financial, legal and commercial claims before money moves.",
        "A convertible note is short-term debt that converts into equity at a later financing round.",
        "Dilution happens when new shares are issued and existing owners' percentage of the company falls.",
        "Vesting makes founders earn their equity over time, which protects the venture if one leaves early.",
        "A personal guarantee makes the founder liable for repayment even when the business is incorporated.",
        "Runway is how many months the venture can operate before the cash runs out at the current burn rate.",
        "Burn rate shows how fast cash is being consumed, which is what determines how long you survive.",
        "Unit economics describe the revenue and cost of one customer or one unit. If they fail, scale makes it worse.",
        "Gross margin tells an investor how much revenue remains after the direct cost of delivering the product.",
        "A sole proprietorship is simplest to start and leaves the owner personally liable for every business debt.",
        "Incorporating gives limited liability, separating personal assets from business debts.",
        "In a general partnership each partner is jointly and severally liable for the partnership's debts.",
        "A partnership agreement should set out profit sharing, decision rights and what happens if a partner exits.",
        "A co-operative is owned and democratically controlled by its members.",
        "A social enterprise pursues a social or environmental mission through commercial activity.",
        "A social entrepreneur measures both financial sustainability and progress against the mission.",
        "Buying a franchise gives an established brand and system in exchange for fees and operating restrictions.",
        "A franchisee trades freedom for a proven system. Resenting the restrictions later is the common mistake.",
        "First-mover advantage is durable only when the head start is converted into something hard to copy.",
        "Network effects, switching costs and proprietary data are defensible. Being early is not.",
        "Switching costs make leaving inconvenient or expensive, so customers stay.",
        "Claiming your advantage is working harder than competitors is a weak position — anyone can match effort.",
        "A niche strategy lets limited resources dominate a small segment rather than fail to register in a large one.",
        "An advantage resting on a two-year exclusive contract expires with the contract.",
        "Test your advantage by asking how quickly a well-resourced competitor could replicate it.",
        "A blue ocean strategy creates uncontested space rather than fighting for share in a crowded one.",
        "A patent grants exclusive use of an invention for a limited period, in exchange for public disclosure.",
        "Copyright in Canada generally arises automatically when an original work is created and fixed in tangible form.",
        "Search existing trademarks and business registrations before committing to a name.",
        "Trade secret protection lasts as long as the secret does, and offers nothing once it leaks.",
        "Licensing earns revenue by permitting another party to use your intellectual property under agreed terms.",
        "Employees and contractors should sign IP assignment agreements, or the creator may keep rights you paid for.",
        "Some open-source licences require derivative works to be released under the same terms. Read before you build.",
        "If a competitor patented the core technology, the practical options are design around it, license it, or pivot.",
        "A subscription model produces predictable recurring revenue and a longer customer relationship.",
        "Churn rate measures the percentage of customers who stop using the product over a period.",
        "In a subscription business, cutting churn is usually cheaper than winning the equivalent new customers.",
        "A freemium model works when the free tier costs little to serve and a meaningful share upgrade.",
        "A marketplace faces the chicken-and-egg problem: neither buyers nor sellers join without the other.",
        "Marketplaces usually solve the cold start by subsidising one side until the other arrives.",
        "A high fixed, low variable cost structure needs volume, but earns strong margins beyond break-even.",
        "Break-even analysis tells a founder how many units must sell before the venture stops losing money.",
        "The opportunity cost of leaving employment is the salary and benefits forgone, and it belongs in the plan.",
        "Calculated risk means accepting uncertainty after assessing the potential loss and the chance of success.",
        "Entrepreneurs are not gamblers. The difference is whether the downside was measured before the bet.",
        "Opportunity is most reliably found by observing an unmet need in a market you already understand.",
        "Copying whatever is trending puts you in a race you started late and understand least.",
        "A customer persona keeps product and marketing decisions anchored to a specific real buyer.",
        "Competitive research must include direct rivals, substitutes, and the customer's option to do nothing.",
        "Doing nothing is the most common competitor and the one most founders forget to plan against.",
        "Selling to businesses means longer sales cycles, more decision makers and larger contract values.",
        "Validate pricing by testing what customers will actually pay against the value they receive.",
        "Pricing from cost alone ignores the only opinion that decides the sale: the buyer's.",
        "A pitch should lead with the problem, who has it, and why this team's solution wins.",
        "Traction in a pitch means evidence customers are adopting and paying — users, revenue, retention.",
        "An advisory board guides without fiduciary duty or formal control. A board of directors has both.",
        "A mentor relationship works when the founder brings specific questions and keeps the decision.",
        "An incubator or accelerator offers mentorship, workspace, networks and sometimes seed funding, often for equity.",
        "Hire first for the critical gaps the founders cannot fill, not for what the founders already do well.",
        "Documenting processes as a venture grows lets new people work consistently without the founder present.",
        "The most common organisational failure past the founding team is founders keeping every decision.",
        "Expanding internationally adds currency fluctuation and unfamiliar regulation to every existing risk.",
        "An exit strategy describes how founders and investors eventually realise the value of their ownership.",
        "Common exits are acquisition, management buyout, or passing the business on. Plan before you need one.",
        "Cash-flow problems kill more small ventures than a lack of profit does.",
        "A brand reduces the customer's perceived risk, which supports both preference and price.",
        "Most first ventures fail. What separates founders is what they learned cheaply and how fast.",
        "A slow market response is a question, not a verdict: is it the message, the product, the price or the audience?",
    ]
}
