//
//  WidgetTips+Business.swift
//  DECAStudyWidget
//
//  Business Management and Administration cluster. Original study notes written
//  for this app — not official DECA Ontario or DECA Inc. material.
//

import Foundation

extension WidgetTips {
    static let businessManagement: [String] = [
        "The four functions of management are planning, organizing, leading and controlling.",
        "Controlling is not about control of people. It is comparing results against the plan and correcting.",
        "Span of control is the number of employees one manager directly supervises.",
        "A tall structure has many levels and narrow spans. A flat one has few levels and wide spans.",
        "Flat structures speed decisions and stretch managers. Tall ones supervise closely and slow everything down.",
        "A functional structure groups people by the work they do: marketing, finance, operations.",
        "A divisional structure groups by product, region or customer, so each division owns its own result.",
        "A matrix structure gives an employee two reporting lines, which is efficient and a constant source of conflict.",
        "An organizational chart shows reporting relationships and lines of authority — not who matters most.",
        "Delegation passes authority and responsibility down while accountability stays with the manager.",
        "Centralised decision-making is consistent. Decentralised decision-making is faster and closer to the customer.",
        "Chain of command is the formal line of authority. Going around it undermines whoever was skipped.",
        "Unity of command says an employee should answer to one supervisor for any one task.",
        "Line positions do the core work. Staff positions advise and support.",
        "Autocratic leadership decides alone. It fits emergencies and wastes a capable team everywhere else.",
        "Democratic leadership involves the team before deciding, which builds buy-in and takes longer.",
        "Laissez-faire leadership delegates fully. It suits experts and abandons novices.",
        "Situational leadership says the right style depends on the task and the team's readiness, not on the leader.",
        "Transformational leaders change what people want. Transactional leaders trade reward for performance.",
        "Maslow's hierarchy runs physiological, safety, belonging, esteem, self-actualisation.",
        "A need already met stops motivating. That is why a pay rise fades faster than managers expect.",
        "Herzberg separated hygiene factors from motivators. Fixing pay and conditions removes dissatisfaction only.",
        "Recognition, responsibility and achievement motivate. Pay and working conditions merely stop demotivating.",
        "Intrinsic motivation comes from the work itself — mastery, autonomy, purpose.",
        "Extrinsic motivation comes from outside: bonuses, prizes, praise. It works fast and wears off.",
        "Theory X assumes people avoid work. Theory Y assumes they seek responsibility. The assumption becomes the culture.",
        "Job enlargement adds tasks at the same level. Job enrichment adds depth, autonomy and decision-making.",
        "Job rotation broadens skills and reduces the risk of one person being the only one who knows something.",
        "Recruitment attracts candidates. Selection chooses among them. They are different problems.",
        "A job description lists duties and responsibilities. A job specification lists what the person needs.",
        "A structured interview asks every candidate the same questions against the same criteria, which reduces bias.",
        "Promoting from within keeps culture and knowledge. Hiring outside brings perspective the room lacks.",
        "Structured onboarding reduces early turnover by making new hires effective and connected sooner.",
        "Orientation is the first days. Onboarding is the first months. Confusing them is why new hires leave.",
        "On-the-job training is cheap and immediate. Off-the-job training is broader and interrupts nothing.",
        "The strongest evidence that training worked is measured on-the-job performance, not attendance or enjoyment.",
        "Performance appraisal should be continuous. An annual review that surprises someone has already failed.",
        "A 360-degree review gathers feedback from managers, peers, direct reports and sometimes customers.",
        "Management by objectives agrees specific objectives with employees, then reviews progress against them.",
        "Feedback lands when it names the behaviour and its effect, and arrives close to the event.",
        "Progressive discipline runs verbal warning, written warning, suspension, then termination.",
        "Documenting performance issues as they happen is what makes a later decision defensible.",
        "Succession planning develops internal candidates for critical roles before those roles fall vacant.",
        "Exit interviews are useful when patterns across many are found and acted on, not filed.",
        "Employee turnover costs recruitment, training and lost productivity — usually far more than a retention effort.",
        "Absenteeism is a symptom. Chronic absence usually points at workload, management or morale.",
        "WHMIS communicates chemical hazards through labels, safety data sheets and training.",
        "A joint health and safety committee brings workers and management together to resolve safety concerns.",
        "Workers have the right to know about hazards, to participate in safety, and to refuse unsafe work.",
        "A supervisor's core safety duty is ensuring safe procedures are followed and hazards are flagged.",
        "Reporting near misses matters because they reveal hazards before anyone is actually hurt.",
        "Ergonomic assessment fits the workstation to the worker, reducing musculoskeletal strain.",
        "Accommodation of a disability is required up to the point of undue hardship for the employer.",
        "An employer must investigate a harassment complaint whenever it becomes aware of an incident.",
        "Whistleblower protection shields employees who report wrongdoing in good faith from reprisal.",
        "Employment standards set minimum wage, overtime, public holidays and required notice of termination.",
        "A restrictive covenant is enforceable when it is reasonable in scope, duration and geography.",
        "A non-disclosure agreement protects confidential information shared with another party.",
        "Vicarious liability means an employer can be responsible for wrongful acts committed in the course of employment.",
        "Monitoring employee email requires, at minimum, a clear written policy that employees know about.",
        "A contract needs offer, acceptance, consideration, capacity and legal purpose.",
        "Consideration is what each side gives up. A promise with nothing exchanged is generally not binding.",
        "A minor's contract for a non-essential item is generally voidable at the minor's option.",
        "Breach of contract is failing to perform an obligation the contract requires, without lawful excuse.",
        "Consumer protection legislation prohibits unfair practices such as false or misleading representations.",
        "A trademark protects a name or logo. A patent protects an invention. Copyright protects an original work.",
        "A privacy policy should say what data is collected, why, how it is used and how long it is kept.",
        "Operations management turns inputs into outputs. Efficiency is the ratio between them.",
        "Efficiency is doing things with minimal waste. Effectiveness is achieving the intended result.",
        "A bottleneck is the step that limits throughput of the whole process. Improving anything else changes nothing.",
        "Total quality management builds quality into every stage and involves everyone, rather than inspecting at the end.",
        "Kaizen is continuous incremental improvement driven by everyone in the organisation.",
        "Lean removes steps that add no value for the customer.",
        "Six Sigma attacks variation, because inconsistent output is its own kind of defect.",
        "A quality circle is a small group of employees meeting regularly to identify and solve work problems.",
        "Benchmarking compares your processes against strong performers to find where the gap actually is.",
        "A standard operating procedure documents the agreed way a task is done so it is consistent and trainable.",
        "Capacity planning matches production capability to expected demand, in both directions.",
        "Supply chain disruption is best mitigated in advance by diversifying suppliers and holding buffer stock.",
        "Single-sourcing a critical component is cheaper until the day it is not available.",
        "Reshoring brings previously offshored production back to the home country.",
        "Outsourcing a non-core function makes sense when a specialist can do it more cheaply or reliably.",
        "Outsourcing something that defines your competitive advantage is how a business gives that advantage away.",
        "Strategic planning has a longer horizon and organisation-wide scope. Operational planning covers the near term.",
        "A mission statement says what the business does, for whom, and why.",
        "A vision statement describes where the business intends to be. A mission says what it does now.",
        "A contingency plan specifies what happens if key assumptions fail.",
        "SMART objectives are specific, measurable, achievable, relevant and time-bound.",
        "A key performance indicator is a measurable value showing progress toward a specific objective.",
        "A leading indicator signals likely future performance while there is still time to act.",
        "A lagging indicator reports results after the period ends. Both are needed; only one is actionable.",
        "A single KPI invites gaming. Measuring call volume alone produces rushed calls and unresolved issues.",
        "A dashboard is useful when it shows a few measures tied to current objectives, not everything collected.",
        "Data-driven decisions require data that is relevant, accurate and interpreted in context.",
        "In Lewin's model, unfreezing builds awareness that change is necessary before anything is changed.",
        "Change initiatives fail most often because leaders under-communicate why the change matters.",
        "Change champions work because peers influence adoption more credibly than instructions from above.",
        "A pilot programme surfaces practical problems at small scale, where fixing them is cheap.",
        "Groupthink is the desire for agreement suppressing dissent and realistic appraisal.",
        "A cross-functional team brings different expertise, so problems get solved with a fuller picture.",
        "Corporate social responsibility means owning the social and environmental effects of your own operations.",
        "A board of directors is responsible for governance and oversight, not day-to-day operations.",
        "Culture is the shared values and norms that shape how people behave when nobody is checking.",
    ]
}
