//
//  WidgetTips+Marketing.swift
//  DECAStudyWidget
//
//  Marketing cluster. Original study notes written for this app — not official
//  DECA Ontario or DECA Inc. material.
//

import Foundation

extension WidgetTips {
    static let marketing: [String] = [
        "The four Ps are product, price, place and promotion. Place means distribution, not the shop's address.",
        "Price skimming launches high to capture early adopters, then falls. Penetration pricing does the opposite.",
        "A loss leader is priced below cost on purpose, to pull shoppers in for everything else in the basket.",
        "Demographic segmentation splits by measurable facts: age, income, gender, education, family size.",
        "Psychographic segmentation splits by lifestyle, values and personality — not by anything on a form.",
        "Behavioural segmentation splits by what people do: usage rate, loyalty, benefit sought, purchase occasion.",
        "Geographic segmentation splits by where people are: country, region, climate, city size, urban or rural.",
        "A useful segment is measurable, accessible, substantial and actionable. Fail any one and it is not worth targeting.",
        "Targeting everyone spreads a budget so thin the message ends up specific to nobody.",
        "Advertising is paid and controlled. Publicity is neither, which is exactly why it is more credible.",
        "The promotional mix is advertising, sales promotion, personal selling, public relations and direct marketing.",
        "A push strategy aims at the channel to stock the product. A pull strategy aims at consumers to ask for it.",
        "Sales promotion buys a short-term spike: coupons, contests, samples, rebates. It rarely builds loyalty.",
        "A product's total offering is the core benefit, the actual product, and the augmented extras around it.",
        "The product life cycle runs introduction, growth, maturity, decline. Profit peaks before sales do.",
        "In the introduction stage profits are usually negative — development and promotion cost more than sales return.",
        "A cash cow has high share in a low-growth market. Milk it to fund the question marks.",
        "A star has high share in a high-growth market. It eats cash now and pays later.",
        "A question mark has low share in a high-growth market. Invest hard or exit; drifting wastes both.",
        "A dog has low share in a low-growth market. Usually a candidate for divestment.",
        "Product mix width counts the lines. Depth counts the items inside one line.",
        "A brand reduces perceived risk. That is why it earns a premium over an identical unbranded product.",
        "Brand equity is the extra value the name adds. It shows up as price tolerance and repeat purchase.",
        "A trademark protects a name, logo or symbol. A patent protects an invention. A copyright protects a work.",
        "Positioning is the place your brand occupies in the buyer's mind relative to competitors, not on a shelf.",
        "A perceptual map plots rival brands on two attributes that matter to buyers, to find the empty space.",
        "A unique selling proposition has to be something rivals cannot easily claim, or it is not unique.",
        "Differentiation earns a premium. Cost leadership earns volume. Trying both usually earns neither.",
        "Elastic demand means a price change moves quantity more than proportionally. Substitutes drive elasticity.",
        "Inelastic demand means quantity barely moves with price. Necessities and habits are inelastic.",
        "Markup is calculated on cost. Margin is calculated on selling price. They are never the same number.",
        "Break-even units equal fixed costs divided by the contribution margin per unit.",
        "Contribution margin is selling price minus variable cost per unit — what each sale contributes to fixed costs.",
        "Prestige pricing sets a high price deliberately, because for some goods the price signals the quality.",
        "Psychological pricing at $9.99 works because buyers read left to right and anchor on the first digit.",
        "Bundle pricing sells several items for less than their total, moving slow stock alongside fast.",
        "Everyday low pricing holds one steady price. High-low pricing swings between full price and promotion.",
        "Cost-plus pricing adds a fixed percentage to cost. Simple, but it ignores what the buyer will actually pay.",
        "Value-based pricing starts from what the benefit is worth to the customer and works backwards to cost.",
        "A channel of distribution is the path from producer to consumer. Fewer steps is not automatically better.",
        "A wholesaler breaks bulk, which lets a small retailer stock variety without meeting each producer's minimum.",
        "Disintermediation removes intermediaries so the producer reaches buyers directly.",
        "Channel conflict happens when a manufacturer starts selling direct while its retailers carry the same line.",
        "Intensive distribution puts a product everywhere. Exclusive distribution restricts it to protect the brand.",
        "Selective distribution sits between the two: enough outlets for reach, few enough to keep standards.",
        "A vertical marketing system coordinates producer, wholesaler and retailer as one unit rather than three.",
        "Just-in-time inventory cuts carrying cost by receiving goods close to when they are needed.",
        "Carrying cost includes storage, insurance, obsolescence and the cash tied up in stock you have not sold.",
        "Reverse logistics handles returns, repairs and recycling — the channel running backwards.",
        "Primary research is collected first-hand for your question. Secondary research already exists.",
        "Secondary research is faster and cheaper, but it was gathered for someone else's question.",
        "Qualitative research explains why, in small numbers. Quantitative research measures how many, at scale.",
        "A focus group explores reasoning. It cannot tell you what share of the market agrees.",
        "A leading question pushes the respondent toward an answer and quietly ruins the data.",
        "Sampling bias means the people you asked do not represent the people you sell to.",
        "A convenience sample is fast and cheap and is the easiest way to survey the wrong people.",
        "Margin of error tells you the range the true figure probably sits in, not the exact answer.",
        "Observation research watches what people actually do, which often differs from what they say they do.",
        "The research process runs: define the problem, design the study, collect, analyse, report, act.",
        "Defining the decision the research must inform comes before choosing any method.",
        "Test marketing launches in one limited area first, so a failure is cheap and local.",
        "A SWOT analysis puts strengths and weaknesses inside the business, opportunities and threats outside.",
        "Staff, brand, patents and facilities are internal. Competitors, law, economy and technology are external.",
        "A situation analysis comes before objectives, so the targets are grounded in something real.",
        "A marketing objective should be specific, measurable and time-bound. \"Be the best\" is none of those.",
        "Market share is your sales divided by total market sales, as a percentage.",
        "Market penetration sells more of an existing product to an existing market — the lowest-risk growth route.",
        "Market development takes an existing product to a new market. Product development does the reverse.",
        "Diversification is a new product in a new market, and carries the most risk of the four growth strategies.",
        "In Porter's five forces, entry threat is lowest where brands are strong and distribution is locked up.",
        "Bargaining power shifts to buyers when there are many suppliers and switching costs are low.",
        "A substitute is not a direct competitor but solves the same problem — coffee against energy drinks.",
        "A marketing audit is a systematic review of the whole marketing operation, not just a list of results.",
        "A buyer persona turns segment data into a specific profile the whole team can design and write for.",
        "The buying process runs: problem recognition, information search, evaluation, purchase, post-purchase.",
        "Post-purchase dissonance is buyer's remorse. Good follow-up reduces returns and protects repeat business.",
        "A high-involvement purchase gets researched. A low-involvement one is habit, and branding matters more.",
        "B2B buying has longer cycles, more decision makers and larger contract values than consumer buying.",
        "Derived demand means business demand depends on consumer demand further down the chain.",
        "Customer lifetime value is the profit expected across the whole relationship, not from one sale.",
        "Keeping a customer usually costs far less than winning a new one, which is why retention is a strategy.",
        "The service recovery paradox: a complaint handled well can leave a customer more loyal than no problem would.",
        "A complaint is a fixable problem you were told about. Silent customers just leave.",
        "Moments of truth are every point of contact where a customer forms a judgement about you.",
        "Empowering front-line staff to resolve issues on the spot fixes problems while the customer is still there.",
        "Service is intangible, inseparable, variable and perishable. Each one creates a different marketing problem.",
        "An unsold hotel room-night or airline seat can never be sold again. That is what perishable means.",
        "Expectations are set by past experience, word of mouth and whatever you promised in your own advertising.",
        "Owned media is what you control. Earned media is what others say. Paid media is what you buy.",
        "Conversion rate is the share of visitors who do the thing you wanted, not the number who saw it.",
        "Search engine optimisation improves unpaid ranking. Paid search buys the slot. They are not the same job.",
        "Content marketing attracts an audience by being useful, rather than by interrupting them.",
        "An influencer with a small, engaged, specific audience often beats a celebrity on cost per real result.",
        "Canadian anti-spam law generally requires consent, clear identification and a working unsubscribe.",
        "Personal information collected in research must be protected and used only as you disclosed.",
        "Answering a negative review publicly is aimed at everyone reading it, not only at the person who wrote it.",
        "Most social traffic is mobile, so a landing page that loads slowly on a phone wastes the whole campaign.",
        "Green marketing only works when the claim is true and specific. Vague claims read as greenwashing.",
        "Cause marketing ties a purchase to a cause. It has to fit the brand or it looks opportunistic.",
        "Ethical marketing means the claim, the price and the small print all say the same thing.",
    ]
}
