//
//  WidgetTips+Finance.swift
//  DECAStudyWidget
//
//  Finance cluster. Original study notes written for this app — not official
//  DECA Ontario or DECA Inc. material.
//

import Foundation

extension WidgetTips {
    static let finance: [String] = [
        "The accounting equation: assets equal liabilities plus owner's equity. It never stops balancing.",
        "A balance sheet is a snapshot on one date. An income statement covers a period.",
        "The cash flow statement splits into operating, investing and financing activities.",
        "Profit is an opinion shaped by accounting policy. Cash is a fact. A profitable month can still run dry.",
        "Depreciation is added back to net income for cash flow because it reduced profit without any cash leaving.",
        "The matching principle records expenses in the same period as the revenues they helped earn.",
        "Accrual accounting records revenue when earned, not when the money arrives.",
        "Revenue recognition happens when the good or service is delivered, not when the order is placed.",
        "Gross profit is revenue minus cost of goods sold, before any operating expense.",
        "Operating profit is gross profit minus operating expenses — the profit from the actual business.",
        "Net income is what remains after interest and tax. It is the bottom line for a reason.",
        "The current ratio is current assets over current liabilities. Around 2:1 is a common rule of thumb.",
        "The quick ratio strips inventory out, because inventory is the current asset hardest to turn into cash.",
        "A current ratio far above the industry norm can mean idle cash or stock that is not moving.",
        "Debt-to-equity shows how much of the business is funded by lenders rather than owners.",
        "High leverage magnifies returns in a good year and losses in a bad one. Interest is owed either way.",
        "Inventory turnover is cost of goods sold divided by average inventory. Low turnover ties up cash.",
        "Days sales outstanding is the average time taken to collect a receivable. Rising DSO is an early warning.",
        "Return on equity measures profit against what the owners put in.",
        "Ratios only mean something against something: last year, a competitor, or the industry average.",
        "What counts as a healthy ratio differs sharply between industries. A grocer and a jeweller are not comparable.",
        "Trend analysis over several years shows direction, which a single year's figures cannot.",
        "Vertical analysis states every line as a percentage of one total, so different-sized firms can be compared.",
        "Horizontal analysis compares the same line across periods to show the change.",
        "A budget plans expected income and spending so actual performance can be measured against something.",
        "A variance is the gap between budget and actual. Favourable is not automatically good — ask why.",
        "A flexible budget adjusts costs to the activity level actually achieved, so the comparison is fair.",
        "Zero-based budgeting justifies every expense from scratch each period rather than inflating last year's.",
        "A master budget consolidates every departmental budget for the whole organisation.",
        "A capital budget covers major long-term assets: buildings, equipment, vehicles.",
        "Involving managers in setting their own budgets improves commitment but invites padding.",
        "A cash budget forecasts timing. A seasonal business needs one even when the annual profit looks fine.",
        "The time value of money: a dollar today can be invested, so it is worth more than a dollar next year.",
        "Present value discounts a future sum back to today. Future value grows a present sum forward.",
        "The Rule of 72 estimates doubling time: divide 72 by the annual rate.",
        "Simple interest is charged on the principal only. Compound interest is charged on the interest too.",
        "Compounding works against a borrower exactly as it works for a saver.",
        "An annual percentage rate expresses the yearly cost of borrowing, which is what makes offers comparable.",
        "Secured debt is backed by collateral, so it costs less. Unsecured debt costs more because the risk is higher.",
        "Debt financing keeps ownership intact and interest is deductible. Equity financing shares the upside.",
        "Equity has no repayment schedule, but the new shareholders own part of every future profit.",
        "Dilution happens when new shares are issued and existing owners' percentage falls.",
        "A bondholder is a lender, paid interest and repaid the principal at maturity. A shareholder is an owner.",
        "Retained earnings are profits kept in the business rather than paid out. They are equity, not cash.",
        "Working capital is current assets minus current liabilities — the cushion for day-to-day operations.",
        "Extending credit lifts sales, ties up cash in receivables and creates the risk of bad debts.",
        "Terms of 2/10 net 30 mean take 2% off if you pay within 10 days, otherwise pay in full within 30.",
        "Stretching payables preserves cash but risks tighter terms, late fees and a damaged supplier relationship.",
        "Checking credit references before extending significant credit is cheaper than chasing the money later.",
        "An aging schedule sorts receivables by how long they have been outstanding.",
        "Leasing suits equipment that dates quickly. Buying suits equipment you will run unchanged for years.",
        "A bank reconciliation explains the difference between your cash records and the bank statement.",
        "Outstanding cheques and deposits in transit are timing differences, not errors.",
        "An overdraft facility lets an account go below zero up to an agreed limit, for a fee.",
        "A credit union is owned by its members, who are also its customers. A chartered bank is owned by shareholders.",
        "The Canada Deposit Insurance Corporation protects eligible deposits at member institutions up to a set limit.",
        "A merchant account is what lets a business accept debit and credit card payments.",
        "An investment dealer underwrites and distributes new share issues. A retail bank takes deposits.",
        "Separation of duties means the person who authorises, the one who records and the one who holds assets differ.",
        "Where staffing is too thin to separate duties, an owner reviewing daily cash and deposits is the practical control.",
        "One person approving orders, receiving goods and approving invoices can create purchases that never existed.",
        "Mandatory vacation is an internal control: a scheme needing constant concealment surfaces while you are away.",
        "An audit trail lets a transaction be traced from source document through to the financial statements.",
        "Internal audit gives independent assurance that controls are actually working, not just written down.",
        "Small businesses suffer fraud disproportionately because thin staffing makes separation of duties hard.",
        "Risk management runs: identify, assess, control, finance, review. Skipping assessment wastes the budget.",
        "Prioritise risks by likelihood combined with potential impact, not by how recently one was noticed.",
        "The four risk responses are avoid, reduce, transfer and accept. Insurance is transfer.",
        "A deductible is what the policyholder pays before coverage starts. A premium keeps the policy in force.",
        "Business interruption insurance covers income lost while operations are suspended after an insured event.",
        "Liability insurance covers harm to others. Property insurance covers your own assets.",
        "Depending on a single supplier for a critical component is concentration risk. Qualify a second one.",
        "A business continuity plan keeps critical operations running or restores them quickly after a disruption.",
        "Break-even analysis assumes price and variable cost per unit hold at every volume. Real life rarely obliges.",
        "The margin of safety shows how far sales can fall before you reach break-even.",
        "Fixed costs stay the same regardless of output. Variable costs move with each unit made.",
        "High fixed and low variable costs mean you need volume, but margins beyond break-even are strong.",
        "Semi-variable costs have both a standing charge and a usage charge. A phone bill is the classic example.",
        "Opportunity cost is the value of the next best alternative you gave up, and it never appears in the ledger.",
        "Sunk costs are already spent and cannot be recovered. They should not influence the next decision.",
        "A progressive tax system taxes higher portions of income at higher rates, not the whole income.",
        "A tax deduction reduces taxable income, so its worth depends on your marginal rate.",
        "A tax credit reduces the tax owed directly, which is why a credit usually beats a deduction of the same size.",
        "CPP and EI deductions on a Canadian pay stub are mandatory contributions, not optional savings.",
        "Gross pay is before deductions. Net pay is what actually reaches the account.",
        "GST and HST are consumption taxes collected by the business and remitted, never kept.",
        "A sole proprietor has unlimited personal liability. Incorporating separates personal assets from business debts.",
        "In a general partnership, partners are jointly and severally liable for the partnership's debts.",
        "A corporation is a separate legal person. It can own property, sign contracts and be sued in its own name.",
        "Amortisation spreads the cost of an intangible asset. Depreciation does the same for a tangible one.",
        "Straight-line depreciation spreads cost evenly. Declining balance front-loads it.",
        "Book value is cost minus accumulated depreciation. It is rarely what the asset would sell for.",
        "A trial balance proves the debits equal the credits. It does not prove the entries were right.",
        "Double-entry bookkeeping records every transaction twice, which is what makes the equation hold.",
        "Debits increase assets and expenses. Credits increase liabilities, equity and revenue.",
        "An accrued expense has been incurred but not yet paid. A prepaid expense is the reverse.",
        "Bad debt expense recognises that some receivables will never be collected.",
        "A contingent liability depends on a future event, such as the outcome of a lawsuit.",
        "Goodwill appears only when one business buys another for more than the fair value of its net assets.",
        "Liquidity is how fast an asset becomes cash without losing value. Cash is perfectly liquid; a building is not.",
    ]
}
